---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Aris.
--- DateTime: 2026/2/8 22:07
---


-- 比较线程标识与锁标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0